// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-fc9Z8eOVES1pYe8l2arAOKsC-6DKqao',
    appId: '1:546737249240:android:a77767a99a332c5f52f0ad',
    messagingSenderId: '546737249240',
    projectId: 'simbaultimate-6fd07',
    storageBucket: 'simbaultimate-6fd07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDOVdfZVDhhSArkhMOg_BuOddJw1sIYk',
    appId: '1:546737249240:ios:b25109881c110d3f52f0ad',
    messagingSenderId: '546737249240',
    projectId: 'simbaultimate-6fd07',
    storageBucket: 'simbaultimate-6fd07.appspot.com',
    iosClientId: '546737249240-nn6sdidj1hltlo54itd4i8vs4hmu9drc.apps.googleusercontent.com',
    iosBundleId: 'co.godson.simbaUltimate',
  );
}
